package com.crud.crud.model;
// Generated 26/10/2022 09:42:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Builder;
import org.hibernate.annotations.GeneratorType;

/**
 * Boleto generated by hbm2java
 */
  @Entity
  @Table(name="boleto"
    ,schema="public"
)
  @Builder
public class boleto  implements java.io.Serializable {


     private int idNoBoleto;
     private double costoBoleto;
     private Date fechaHoraReserva;
     private Integer cantidaEquipaje;
     private Integer pesoEquipaje;
     private String puertaEmbarque;
     private int idAsiento;
     private int idVuelo;
     private int idClientes;

    public boleto() {
    }

	
    public boleto(int idNoBoleto, double costoBoleto, int idAsiento, int idVuelo, int idClientes) {
        this.idNoBoleto = idNoBoleto;
        this.costoBoleto = costoBoleto;
        this.idAsiento = idAsiento;
        this.idVuelo = idVuelo;
        this.idClientes = idClientes;
    }
    public boleto(int idNoBoleto, double costoBoleto, Date fechaHoraReserva, Integer cantidaEquipaje, Integer pesoEquipaje, String puertaEmbarque, int idAsiento, int idVuelo, int idClientes) {
       this.idNoBoleto = idNoBoleto;
       this.costoBoleto = costoBoleto;
       this.fechaHoraReserva = fechaHoraReserva;
       this.cantidaEquipaje = cantidaEquipaje;
       this.pesoEquipaje = pesoEquipaje;
       this.puertaEmbarque = puertaEmbarque;
       this.idAsiento = idAsiento;
       this.idVuelo = idVuelo;
       this.idClientes = idClientes;
    }
   
     @Id 

    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_no_boleto", unique=true, nullable=false)
    public int getIdNoBoleto() {
        return this.idNoBoleto;
    }
    
    public void setIdNoBoleto(int idNoBoleto) {
        this.idNoBoleto = idNoBoleto;
    }

    
    @Column(name="costo_boleto", nullable=false, precision=17, scale=17)
    public double getCostoBoleto() {
        return this.costoBoleto;
    }
    
    public void setCostoBoleto(double costoBoleto) {
        this.costoBoleto = costoBoleto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_hora_reserva", length=29)
    public Date getFechaHoraReserva() {
        return this.fechaHoraReserva;
    }
    
    public void setFechaHoraReserva(Date fechaHoraReserva) {
        this.fechaHoraReserva = fechaHoraReserva;
    }

    
    @Column(name="cantida_equipaje")
    public Integer getCantidaEquipaje() {
        return this.cantidaEquipaje;
    }
    
    public void setCantidaEquipaje(Integer cantidaEquipaje) {
        this.cantidaEquipaje = cantidaEquipaje;
    }

    
    @Column(name="peso_equipaje")
    public Integer getPesoEquipaje() {
        return this.pesoEquipaje;
    }
    
    public void setPesoEquipaje(Integer pesoEquipaje) {
        this.pesoEquipaje = pesoEquipaje;
    }

    
    @Column(name="puerta_embarque", length=16)
    public String getPuertaEmbarque() {
        return this.puertaEmbarque;
    }
    
    public void setPuertaEmbarque(String puertaEmbarque) {
        this.puertaEmbarque = puertaEmbarque;
    }

    
    @Column(name="id_asiento", nullable=false)
    public int getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(int idAsiento) {
        this.idAsiento = idAsiento;
    }

    
    @Column(name="id_vuelo", nullable=false)
    public int getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(int idVuelo) {
        this.idVuelo = idVuelo;
    }

    
    @Column(name="id_clientes", nullable=false)
    public int getIdClientes() {
        return this.idClientes;
    }
    
    public void setIdClientes(int idClientes) {
        this.idClientes = idClientes;
    }




}


