package com.crud.crud.model;
// Generated 26/10/2022 09:55:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name="vuelo"
    ,schema="public"
)
public class vuelo  implements java.io.Serializable {


     private int idVuelo;
     private String destino;
     private Date fechaSalida;
     private Date fechaLlegada;
     private double costoAsientos;
     private String estadoVuelo;
     private String usuarioCrea;
     private String usuarioModifica;
     private int idAvion;
     private int idTripulacion;

    public vuelo() {
    }

    public vuelo(int idVuelo, String destino, Date fechaSalida, Date fechaLlegada, double costoAsientos, String estadoVuelo, String usuarioCrea, String usuarioModifica, int idAvion, int idTripulacion) {
        this.idVuelo = idVuelo;
        this.destino = destino;
        this.fechaSalida = fechaSalida;
        this.fechaLlegada = fechaLlegada;
        this.costoAsientos = costoAsientos;
        this.estadoVuelo = estadoVuelo;
        this.usuarioCrea = usuarioCrea;
        this.usuarioModifica = usuarioModifica;
        this.idAvion = idAvion;
        this.idTripulacion = idTripulacion;
    }

  
   
     @Id 
    @Column(name="id_vuelo", unique=true, nullable=false)
     @GeneratedValue(strategy = IDENTITY)
    public int getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(int idVuelo) {
        this.idVuelo = idVuelo;
    }

    
    @Column(name="destino", nullable=false, length=50)
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_salida", nullable=false, length=13)
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_llegada", nullable=false, length=13)
    public Date getFechaLlegada() {
        return this.fechaLlegada;
    }
    
    public void setFechaLlegada(Date fechaLlegada) {
        this.fechaLlegada = fechaLlegada;
    }

    
    @Column(name="costo_asientos", nullable=false, precision=17, scale=17)
    public double getCostoAsientos() {
        return this.costoAsientos;
    }
    
    public void setCostoAsientos(double costoAsientos) {
        this.costoAsientos = costoAsientos;
    }

    
    @Column(name="estado_vuelo", nullable=false, length=16)
    public String getEstadoVuelo() {
        return this.estadoVuelo;
    }
    
    public void setEstadoVuelo(String estadoVuelo) {
        this.estadoVuelo = estadoVuelo;
    }

    
    @Column(name="usuario_crea", nullable=false, length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    
    @Column(name="id_avion", nullable=false)
    public int getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }

    
    @Column(name="id_tripulacion", nullable=false)
    public int getIdTripulacion() {
        return this.idTripulacion;
    }
    
    public void setIdTripulacion(int idTripulacion) {
        this.idTripulacion = idTripulacion;
    }




}


